name: Deploy
on:
  push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: pwsh
      env:
        EMAIL: ${{ secrets.EMAIL }}
        USER: ${{ secrets.USER }}
      run: |
        git config --global user.email "$env:EMAIL"
        git config --global user.name "$env:USER"
        git add . -f
        git commit --message 'release'
        git push